# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import inference_pb2 as inference__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GatewayServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Infer = channel.unary_unary(
                '/inference.GatewayService/Infer',
                request_serializer=inference__pb2.InferRequest.SerializeToString,
                response_deserializer=inference__pb2.InferResponse.FromString,
                _registered_method=True)
        self.GetMetrics = channel.unary_unary(
                '/inference.GatewayService/GetMetrics',
                request_serializer=inference__pb2.MetricsRequest.SerializeToString,
                response_deserializer=inference__pb2.GatewayMetrics.FromString,
                _registered_method=True)


class GatewayServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Infer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Infer': grpc.unary_unary_rpc_method_handler(
                    servicer.Infer,
                    request_deserializer=inference__pb2.InferRequest.FromString,
                    response_serializer=inference__pb2.InferResponse.SerializeToString,
            ),
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=inference__pb2.MetricsRequest.FromString,
                    response_serializer=inference__pb2.GatewayMetrics.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inference.GatewayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inference.GatewayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GatewayService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Infer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inference.GatewayService/Infer',
            inference__pb2.InferRequest.SerializeToString,
            inference__pb2.InferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inference.GatewayService/GetMetrics',
            inference__pb2.MetricsRequest.SerializeToString,
            inference__pb2.GatewayMetrics.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PrefillServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunPrefill = channel.unary_unary(
                '/inference.PrefillService/RunPrefill',
                request_serializer=inference__pb2.PrefillRequest.SerializeToString,
                response_deserializer=inference__pb2.PrefillResponse.FromString,
                _registered_method=True)
        self.GetMetrics = channel.unary_unary(
                '/inference.PrefillService/GetMetrics',
                request_serializer=inference__pb2.MetricsRequest.SerializeToString,
                response_deserializer=inference__pb2.WorkerMetrics.FromString,
                _registered_method=True)


class PrefillServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunPrefill(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrefillServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunPrefill': grpc.unary_unary_rpc_method_handler(
                    servicer.RunPrefill,
                    request_deserializer=inference__pb2.PrefillRequest.FromString,
                    response_serializer=inference__pb2.PrefillResponse.SerializeToString,
            ),
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=inference__pb2.MetricsRequest.FromString,
                    response_serializer=inference__pb2.WorkerMetrics.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inference.PrefillService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inference.PrefillService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PrefillService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunPrefill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inference.PrefillService/RunPrefill',
            inference__pb2.PrefillRequest.SerializeToString,
            inference__pb2.PrefillResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inference.PrefillService/GetMetrics',
            inference__pb2.MetricsRequest.SerializeToString,
            inference__pb2.WorkerMetrics.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DecodeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunDecode = channel.unary_stream(
                '/inference.DecodeService/RunDecode',
                request_serializer=inference__pb2.DecodeRequest.SerializeToString,
                response_deserializer=inference__pb2.DecodeResponse.FromString,
                _registered_method=True)
        self.GetMetrics = channel.unary_unary(
                '/inference.DecodeService/GetMetrics',
                request_serializer=inference__pb2.MetricsRequest.SerializeToString,
                response_deserializer=inference__pb2.WorkerMetrics.FromString,
                _registered_method=True)


class DecodeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunDecode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DecodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunDecode': grpc.unary_stream_rpc_method_handler(
                    servicer.RunDecode,
                    request_deserializer=inference__pb2.DecodeRequest.FromString,
                    response_serializer=inference__pb2.DecodeResponse.SerializeToString,
            ),
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=inference__pb2.MetricsRequest.FromString,
                    response_serializer=inference__pb2.WorkerMetrics.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inference.DecodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inference.DecodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DecodeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunDecode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/inference.DecodeService/RunDecode',
            inference__pb2.DecodeRequest.SerializeToString,
            inference__pb2.DecodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inference.DecodeService/GetMetrics',
            inference__pb2.MetricsRequest.SerializeToString,
            inference__pb2.WorkerMetrics.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
