# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import inference_pb2 as inference__pb2


class GatewayServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Infer = channel.unary_unary(
        '/inference.GatewayService/Infer',
        request_serializer=inference__pb2.InferRequest.SerializeToString,
        response_deserializer=inference__pb2.InferResponse.FromString,
        )
    self.GetMetrics = channel.unary_unary(
        '/inference.GatewayService/GetMetrics',
        request_serializer=inference__pb2.MetricsRequest.SerializeToString,
        response_deserializer=inference__pb2.GatewayMetrics.FromString,
        )


class GatewayServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Infer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMetrics(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GatewayServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Infer': grpc.unary_unary_rpc_method_handler(
          servicer.Infer,
          request_deserializer=inference__pb2.InferRequest.FromString,
          response_serializer=inference__pb2.InferResponse.SerializeToString,
      ),
      'GetMetrics': grpc.unary_unary_rpc_method_handler(
          servicer.GetMetrics,
          request_deserializer=inference__pb2.MetricsRequest.FromString,
          response_serializer=inference__pb2.GatewayMetrics.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'inference.GatewayService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class PrefillServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RunPrefill = channel.unary_unary(
        '/inference.PrefillService/RunPrefill',
        request_serializer=inference__pb2.PrefillRequest.SerializeToString,
        response_deserializer=inference__pb2.PrefillResponse.FromString,
        )
    self.GetMetrics = channel.unary_unary(
        '/inference.PrefillService/GetMetrics',
        request_serializer=inference__pb2.MetricsRequest.SerializeToString,
        response_deserializer=inference__pb2.WorkerMetrics.FromString,
        )


class PrefillServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def RunPrefill(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMetrics(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PrefillServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RunPrefill': grpc.unary_unary_rpc_method_handler(
          servicer.RunPrefill,
          request_deserializer=inference__pb2.PrefillRequest.FromString,
          response_serializer=inference__pb2.PrefillResponse.SerializeToString,
      ),
      'GetMetrics': grpc.unary_unary_rpc_method_handler(
          servicer.GetMetrics,
          request_deserializer=inference__pb2.MetricsRequest.FromString,
          response_serializer=inference__pb2.WorkerMetrics.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'inference.PrefillService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class DecodeServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RunDecode = channel.unary_stream(
        '/inference.DecodeService/RunDecode',
        request_serializer=inference__pb2.DecodeRequest.SerializeToString,
        response_deserializer=inference__pb2.DecodeResponse.FromString,
        )
    self.GetMetrics = channel.unary_unary(
        '/inference.DecodeService/GetMetrics',
        request_serializer=inference__pb2.MetricsRequest.SerializeToString,
        response_deserializer=inference__pb2.WorkerMetrics.FromString,
        )


class DecodeServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def RunDecode(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMetrics(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DecodeServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RunDecode': grpc.unary_stream_rpc_method_handler(
          servicer.RunDecode,
          request_deserializer=inference__pb2.DecodeRequest.FromString,
          response_serializer=inference__pb2.DecodeResponse.SerializeToString,
      ),
      'GetMetrics': grpc.unary_unary_rpc_method_handler(
          servicer.GetMetrics,
          request_deserializer=inference__pb2.MetricsRequest.FromString,
          response_serializer=inference__pb2.WorkerMetrics.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'inference.DecodeService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
